from tests.compiler.punkt_compiler_test_helper import PunktCompilerTestHelper


class TestArray(object):
    """ General array test suite. """

    def setup_class(self):
        self._compile_helper = PunktCompilerTestHelper()

    def test_bad_array_1(self):
        try:
            self._compile_helper.compile_with_failure()
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_bad_array_2(self):
        try:
            self._compile_helper.compile_with_failure()
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_bad_array_3(self):
        try:
            self._compile_helper.compile_with_failure()
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_bad_array_4(self):
        try:
            self._compile_helper.compile_with_failure()
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_bad_array_5(self):
        try:
            self._compile_helper.compile_with_failure()
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_bad_array_6(self):
        try:
            self._compile_helper.compile_with_failure()
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_bad_array_7(self):
        try:
            self._compile_helper.compile_with_failure()
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_bad_array_8(self):
        try:
            self._compile_helper.compile_with_failure()
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_bad_array_9(self):
        try:
            self._compile_helper.compile_with_failure()
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_bad_array_10(self):
        try:
            self._compile_helper.compile_with_failure()
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_bad_array_11(self):
        try:
            self._compile_helper.compile_with_failure()
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_bad_array_12(self):
        try:
            self._compile_helper.compile_with_failure()
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_bad_array_13(self):
        try:
            self._compile_helper.compile_with_failure()
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_bad_array_14(self):
        try:
            self._compile_helper.compile_with_failure()
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_bad_array_15(self):
        try:
            self._compile_helper.compile_with_failure()
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_bad_array_16(self):
        try:
            self._compile_helper.compile_with_failure()
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_bad_array_17(self):
        try:
            self._compile_helper.compile_with_failure()
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_bad_array_18(self):
        try:
            self._compile_helper.compile_with_failure()
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_bad_array_19(self):
        try:
            self._compile_helper.compile_with_failure()
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_bad_array_20(self):
        try:
            self._compile_helper.compile_with_failure()
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_bad_array_21(self):
        try:
            self._compile_helper.compile_with_failure()
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_bad_array_22(self):
        try:
            self._compile_helper.compile_with_failure()
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_bad_array_23(self):
        try:
            self._compile_helper.compile_with_failure()
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_good_array_1(self):
        try:
            actual_output_path = self._compile_helper.compile_with_success()
            self._compile_helper.verify_actual_output(actual_output_path)
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_good_array_2(self):
        try:
            actual_output_path = self._compile_helper.compile_with_success()
            self._compile_helper.verify_actual_output(actual_output_path)
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_good_array_3(self):
        try:
            actual_output_path = self._compile_helper.compile_with_success()
            self._compile_helper.verify_actual_output(actual_output_path)
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_good_array_4(self):
        try:
            actual_output_path = self._compile_helper.compile_with_success()
            self._compile_helper.verify_actual_output(actual_output_path)
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_good_array_5(self):
        try:
            actual_output_path = self._compile_helper.compile_with_success()
            self._compile_helper.verify_actual_output(actual_output_path)
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_good_array_6(self):
        try:
            actual_output_path = self._compile_helper.compile_with_success()
            self._compile_helper.verify_actual_output(actual_output_path)
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_good_array_7(self):
        try:
            actual_output_path = self._compile_helper.compile_with_success()
            self._compile_helper.verify_actual_output(actual_output_path)
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_good_array_8(self):
        try:
            actual_output_path = self._compile_helper.compile_with_success()
            self._compile_helper.verify_actual_output(actual_output_path)
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_good_array_9(self):
        try:
            actual_output_path = self._compile_helper.compile_with_success()
            self._compile_helper.verify_actual_output(actual_output_path)
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_good_array_10(self):
        try:
            actual_output_path = self._compile_helper.compile_with_success()
            self._compile_helper.verify_actual_output(actual_output_path)
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_good_array_11(self):
        try:
            actual_output_path = self._compile_helper.compile_with_success()
            self._compile_helper.verify_actual_output(actual_output_path)
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_good_array_12(self):
        try:
            actual_output_path = self._compile_helper.compile_with_success()
            self._compile_helper.verify_actual_output(actual_output_path)
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_good_array_13(self):
        try:
            actual_output_path = self._compile_helper.compile_with_success()
            self._compile_helper.verify_actual_output(actual_output_path)
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_good_array_14(self):
        try:
            actual_output_path = self._compile_helper.compile_with_success()
            self._compile_helper.verify_actual_output(actual_output_path)
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_good_array_15(self):
        try:
            actual_output_path = self._compile_helper.compile_with_success()
            self._compile_helper.verify_actual_output(actual_output_path)
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_good_array_16(self):
        try:
            actual_output_path = self._compile_helper.compile_with_success()
            self._compile_helper.verify_actual_output(actual_output_path)
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_good_array_17(self):
        try:
            actual_output_path = self._compile_helper.compile_with_success()
            self._compile_helper.verify_actual_output(actual_output_path)
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_good_array_18(self):
        try:
            actual_output_path = self._compile_helper.compile_with_success()
            self._compile_helper.verify_actual_output(actual_output_path)
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_good_array_19(self):
        try:
            actual_output_path = self._compile_helper.compile_with_success()
            self._compile_helper.verify_actual_output(actual_output_path)
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_good_array_20(self):
        try:
            actual_output_path = self._compile_helper.compile_with_success()
            self._compile_helper.verify_actual_output(actual_output_path)
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_good_array_21(self):
        try:
            actual_output_path = self._compile_helper.compile_with_success()
            self._compile_helper.verify_actual_output(actual_output_path)
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_good_array_22(self):
        try:
            actual_output_path = self._compile_helper.compile_with_success()
            self._compile_helper.verify_actual_output(actual_output_path)
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_good_array_23(self):
        try:
            actual_output_path = self._compile_helper.compile_with_success()
            self._compile_helper.verify_actual_output(actual_output_path)
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_good_array_24(self):
        try:
            actual_output_path = self._compile_helper.compile_with_success()
            self._compile_helper.verify_actual_output(actual_output_path)
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_good_array_25(self):
        try:
            actual_output_path = self._compile_helper.compile_with_success()
            self._compile_helper.verify_actual_output(actual_output_path)
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_good_array_26(self):
        try:
            actual_output_path = self._compile_helper.compile_with_success()
            self._compile_helper.verify_actual_output(actual_output_path)
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_good_array_27(self):
        try:
            actual_output_path = self._compile_helper.compile_with_success()
            self._compile_helper.verify_actual_output(actual_output_path)
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_good_array_28(self):
        try:
            actual_output_path = self._compile_helper.compile_with_success()
            self._compile_helper.verify_actual_output(actual_output_path)
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_good_array_29(self):
        try:
            actual_output_path = self._compile_helper.compile_with_success()
            self._compile_helper.verify_actual_output(actual_output_path)
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_good_array_30(self):
        try:
            actual_output_path = self._compile_helper.compile_with_success()
            self._compile_helper.verify_actual_output(actual_output_path)
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_good_array_31(self):
        try:
            actual_output_path = self._compile_helper.compile_with_success()
            self._compile_helper.verify_actual_output(actual_output_path)
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_good_array_32(self):
        try:
            actual_output_path = self._compile_helper.compile_with_success()
            self._compile_helper.verify_actual_output(actual_output_path)
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_good_array_33(self):
        try:
            actual_output_path = self._compile_helper.compile_with_success()
            self._compile_helper.verify_actual_output(actual_output_path)
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_good_array_34(self):
        try:
            actual_output_path = self._compile_helper.compile_with_success()
            self._compile_helper.verify_actual_output(actual_output_path)
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)

    def test_good_array_35(self):
        try:
            actual_output_path = self._compile_helper.compile_with_success()
            self._compile_helper.verify_actual_output(actual_output_path)
        except RuntimeError as ex:
            assert False, "Exception was raised: " + repr(ex)
